// Auto-PR generator — opens a "Set up InariWatch" pull request on the
// user's repo on GitHub App install. Adds:
//
//   - instrumentation.ts        (new file)
//   - next.config.ts wrap        (edit, if it's a Next.js project)
//   - package.json dep add       (edit, adds @inariwatch/capture)
//
// On branch `inariwatch/setup`. User just clicks Merge once.
//
// Framework support: Next.js (primary). Nuxt, Express, Hono fall back to
// a simpler "import @inariwatch/capture/auto" entry — handled in
// `pickRecipe`. We never touch repos missing a package.json.
//
// The user's INARIWATCH_DSN is included verbatim in the PR body so they
// can paste it into their hosting provider's env vars (Vercel, Netlify,
// Render, Railway, Fly, Heroku, etc.) right after merging.

import { ghFetch } from "./octokit";

const BRANCH = "inariwatch/setup";
const CAPTURE_DEP_VERSION = "^0.10.2";

const INSTRUMENTATION_TS_NEXT = `// Auto-init InariWatch error capture. Generated by the InariWatch
// GitHub App on first install — feel free to edit or remove. See
// https://inariwatch.com/docs/quickstart for details.
import "@inariwatch/capture/auto";
import { captureRequestError } from "@inariwatch/capture";
export const onRequestError = captureRequestError;
`;

const INSTRUMENTATION_TS_GENERIC = `// Auto-init InariWatch error capture. Generated by the InariWatch
// GitHub App on first install. Import this from your entry point so it
// runs once at boot.
import "@inariwatch/capture/auto";
`;

interface OpenedPR {
  url:    string;
  owner:  string;
  repo:   string;
  number: number;
}

interface RepoInfo { default_branch: string }

interface ContentResp {
  type:    string;
  content: string;
  sha:     string;
}

interface InstallationRepoList {
  repositories: Array<{ name: string; owner: { login: string } }>;
}

/** Open the auto-PR on every repo the user authorized. Returns the first PR opened. */
export async function openSetupPRForInstallation(
  installationToken: string,
  dsn:               string,
): Promise<OpenedPR[]> {
  const repos = await listRepos(installationToken);
  const opened: OpenedPR[] = [];
  for (const r of repos) {
    try {
      const pr = await openSetupPR(installationToken, r.owner.login, r.name, dsn);
      if (pr) opened.push(pr);
    } catch (err) {
      console.warn(`[github-app] auto-PR failed for ${r.owner.login}/${r.name}:`, err instanceof Error ? err.message : err);
    }
  }
  return opened;
}

async function listRepos(token: string): Promise<InstallationRepoList["repositories"]> {
  const res = await ghFetch(token, "/installation/repositories?per_page=100");
  if (!res.ok) throw new Error(`listRepos: ${res.status}`);
  const json = (await res.json()) as InstallationRepoList;
  return json.repositories ?? [];
}

export async function openSetupPR(
  token: string,
  owner: string,
  repo:  string,
  dsn:   string,
): Promise<OpenedPR | null> {
  // 1. Repo metadata.
  const repoRes = await ghFetch(token, `/repos/${owner}/${repo}`);
  if (!repoRes.ok) throw new Error(`GET /repos: ${repoRes.status}`);
  const { default_branch: base } = (await repoRes.json()) as RepoInfo;

  // 2. Detect framework from package.json on default branch.
  const pkgFile = await getContent(token, owner, repo, "package.json", base);
  if (!pkgFile) {
    console.log(`[github-app] ${owner}/${repo}: no package.json — skipping`);
    return null;
  }
  const pkgRaw = decodeContent(pkgFile.content);
  const pkg = safeParseJSON<{ dependencies?: Record<string, string>; devDependencies?: Record<string, string> }>(pkgRaw);
  if (!pkg) return null;
  const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
  const recipe = pickRecipe(deps);

  // 3. Skip if already integrated.
  if (deps["@inariwatch/capture"]) {
    const instr = await getContent(token, owner, repo, "instrumentation.ts", base);
    if (instr) {
      console.log(`[github-app] ${owner}/${repo}: already integrated — skipping`);
      return null;
    }
  }

  // 4. Create branch (idempotent — 422 means it exists).
  const baseRef = await ghFetch(token, `/repos/${owner}/${repo}/git/ref/heads/${base}`);
  if (!baseRef.ok) throw new Error(`get ref: ${baseRef.status}`);
  const baseSha = ((await baseRef.json()) as { object: { sha: string } }).object.sha;

  const createBranch = await ghFetch(token, `/repos/${owner}/${repo}/git/refs`, {
    method: "POST",
    json:   { ref: `refs/heads/${BRANCH}`, sha: baseSha },
  });
  if (!createBranch.ok && createBranch.status !== 422) {
    throw new Error(`create branch: ${createBranch.status} ${await createBranch.text()}`);
  }

  // 5. PUT instrumentation.ts (new — no sha).
  if (!(await getContent(token, owner, repo, "instrumentation.ts", BRANCH))) {
    await putContent(token, owner, repo, "instrumentation.ts", recipe.instrumentation, undefined, "chore(inariwatch): add instrumentation.ts");
  }

  // 6. Wrap next.config.* if Next.js.
  if (recipe.framework === "nextjs") {
    for (const cfg of ["next.config.ts", "next.config.mjs", "next.config.js"]) {
      const f = await getContent(token, owner, repo, cfg, BRANCH);
      if (!f) continue;
      const src = decodeContent(f.content);
      const wrapped = wrapNextConfig(src);
      if (wrapped) {
        await putContent(token, owner, repo, cfg, wrapped, f.sha, "chore(inariwatch): wrap next.config");
      }
      break;
    }
  }

  // 7. Add @inariwatch/capture to package.json on the branch.
  if (!deps["@inariwatch/capture"]) {
    const branchPkg = await getContent(token, owner, repo, "package.json", BRANCH);
    if (branchPkg) {
      const branchRaw = decodeContent(branchPkg.content);
      const updated = addDependencyJSON(branchRaw, "@inariwatch/capture", CAPTURE_DEP_VERSION);
      if (updated) {
        await putContent(token, owner, repo, "package.json", updated, branchPkg.sha, "chore(inariwatch): add @inariwatch/capture");
      }
    }
  }

  // 8. Open PR.
  const pr = await ghFetch(token, `/repos/${owner}/${repo}/pulls`, {
    method: "POST",
    json: {
      title: "Set up InariWatch error monitoring",
      head:  BRANCH,
      base,
      body:  prBody(recipe, dsn),
    },
  });
  if (!pr.ok) {
    if (pr.status === 422) {
      // PR may already exist — fetch and return.
      const existingRes = await ghFetch(
        token,
        `/repos/${owner}/${repo}/pulls?state=open&head=${owner}:${BRANCH}`,
      );
      if (existingRes.ok) {
        const arr = (await existingRes.json()) as Array<{ html_url: string; number: number }>;
        if (arr[0]) return { url: arr[0].html_url, owner, repo, number: arr[0].number };
      }
    }
    throw new Error(`create PR: ${pr.status} ${await pr.text()}`);
  }
  const prJson = (await pr.json()) as { html_url: string; number: number };
  return { url: prJson.html_url, owner, repo, number: prJson.number };
}

// ── helpers ──────────────────────────────────────────────────────────────────

interface Recipe {
  framework: "nextjs" | "nuxt" | "node";
  instrumentation: string;
}

function pickRecipe(deps: Record<string, string>): Recipe {
  if (deps["next"])  return { framework: "nextjs", instrumentation: INSTRUMENTATION_TS_NEXT };
  if (deps["nuxt"])  return { framework: "nuxt",   instrumentation: INSTRUMENTATION_TS_GENERIC };
  return { framework: "node", instrumentation: INSTRUMENTATION_TS_GENERIC };
}

async function getContent(
  token: string,
  owner: string,
  repo:  string,
  path:  string,
  ref:   string,
): Promise<ContentResp | null> {
  const res = await ghFetch(token, `/repos/${owner}/${repo}/contents/${path}?ref=${encodeURIComponent(ref)}`);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`getContent ${path}: ${res.status}`);
  return (await res.json()) as ContentResp;
}

async function putContent(
  token:    string,
  owner:    string,
  repo:     string,
  path:     string,
  content:  string,
  sha:      string | undefined,
  message:  string,
): Promise<void> {
  const body: Record<string, string> = {
    message,
    branch:  BRANCH,
    content: Buffer.from(content, "utf8").toString("base64"),
  };
  if (sha) body.sha = sha;
  const res = await ghFetch(token, `/repos/${owner}/${repo}/contents/${path}`, {
    method: "PUT",
    json:   body,
  });
  if (!res.ok) throw new Error(`putContent ${path}: ${res.status} ${await res.text()}`);
}

function decodeContent(b64: string): string {
  return Buffer.from(b64, "base64").toString("utf8");
}

function safeParseJSON<T>(raw: string): T | null {
  try { return JSON.parse(raw) as T; } catch { return null; }
}

function wrapNextConfig(src: string): string | null {
  if (src.includes("withInariWatch")) return null;
  const importLine = `import { withInariWatch } from "@inariwatch/capture/next";\n`;
  // Two common patterns: `export default <ident>` and `module.exports = <ident>`.
  if (/export\s+default\s+\w+/.test(src)) {
    return importLine + src.replace(/export\s+default\s+(\w+)/, "export default withInariWatch($1)");
  }
  if (/module\.exports\s*=\s*\w+/.test(src)) {
    return src.replace(/module\.exports\s*=\s*(\w+)/, `module.exports = require("@inariwatch/capture/next").withInariWatch($1)`);
  }
  // Last-ditch: wrap a literal object export.
  return importLine + src.replace(
    /export\s+default\s+(\{[\s\S]*?\});?/,
    "export default withInariWatch($1);",
  );
}

function addDependencyJSON(raw: string, name: string, version: string): string | null {
  const pkg = safeParseJSON<Record<string, unknown>>(raw);
  if (!pkg) return null;
  const deps = (pkg.dependencies as Record<string, string>) ?? {};
  if (deps[name]) return null; // already present, skip
  pkg.dependencies = { ...deps, [name]: version };
  // Preserve a trailing newline like git/hub's pretty-print does.
  return JSON.stringify(pkg, null, 2) + "\n";
}

function prBody(recipe: Recipe, dsn: string): string {
  const fwTitle = {
    nextjs: "Next.js",
    nuxt:   "Nuxt",
    node:   "Node.js",
  }[recipe.framework];
  return `## InariWatch error monitoring

This PR wires your **${fwTitle}** app to [InariWatch](https://inariwatch.com) — AI-powered error monitoring with auto-remediation. Generated by the [InariWatch GitHub App](https://github.com/apps/inariwatch). Everything below is reversible — just close the PR if you change your mind.

### What changed

- \`instrumentation.ts\` — registers \`@inariwatch/capture\` at boot.
${recipe.framework === "nextjs" ? "- `next.config.*` — wrapped with `withInariWatch()` so build-time errors surface in your dashboard.\n" : ""}- \`package.json\` — adds \`@inariwatch/capture\` (~12kb gzip, zero runtime dependencies).

### One thing to do after merging

Add this environment variable to your hosting provider:

\`\`\`
INARIWATCH_DSN=${dsn}
\`\`\`

Quick links for common providers:

| Provider | Where to paste it |
|----------|-------------------|
| **Vercel** | Project → Settings → Environment Variables → \`INARIWATCH_DSN\` for Production / Preview / Development |
| **Netlify** | Site settings → Environment variables → \`INARIWATCH_DSN\` |
| **Render** | Web Service → Environment → Add environment variable |
| **Railway** | Project → Variables → \`INARIWATCH_DSN\` |
| **Fly.io** | \`flyctl secrets set INARIWATCH_DSN=...\` |
| **Heroku** | Settings → Config Vars |
| **AWS / self-host** | Add to your existing secrets manager / \`.env\` |

Then redeploy. Every uncaught error from that point on streams to **app.inariwatch.com** with AI auto-diagnosis.

### What you get

- Real-time error capture with full stack traces, request context, and breadcrumbs.
- AI auto-diagnosis on every alert (free, no API key required from you).
- One-click auto-remediation PRs — InariWatch generates a fix branch + PR you review.
- Substrate I/O recording (optional) for deterministic replay of production crashes.

### Docs

- Quickstart: <https://app.inariwatch.com/docs/quickstart>
- API reference: <https://app.inariwatch.com/docs/api>
- Questions: <hello@inariwatch.com>

---

*This PR was generated automatically when you installed the InariWatch GitHub App. To stop monitoring, uninstall the App at <https://github.com/settings/installations> — your code stays as-is, the SDK simply has no DSN to send to.*`;
}
