/**
 * Staging E2E Verification
 *
 * Generates a GitHub Actions workflow that:
 * 1. Checks out the fix branch
 * 2. Installs dependencies and builds the app
 * 3. Starts the app in test/preview mode
 * 4. Runs Playwright E2E tests against it
 * 5. Reports pass/fail as a check run
 *
 * The workflow runs automatically when pushed to a fix branch.
 * The remediation pipeline polls for the check run result.
 */

import * as gh from "@/lib/services/github-api";

// ── Types ────────────────────────────────────────────────────────────────────

export type E2EFramework =
  | "nextjs"
  | "nuxt"
  | "remix"
  | "sveltekit"
  | "astro"
  | "vite"
  | "express"
  | "fastify"
  | "nest"
  | "generic";

export interface E2EConfig {
  framework: E2EFramework;
  startCommand: string;
  port: number;
  testCommand: string;
  installCommand: string;
  buildCommand: string;
}

export interface E2EResult {
  passed: boolean;
  testCount: number;
  failedCount: number;
  duration: number;  // seconds
  logs: string;
}

// ── Auto-detect project framework ────────────────────────────────────────────

export async function detectE2EConfig(
  token: string,
  owner: string,
  repo: string,
  ref: string
): Promise<E2EConfig | null> {
  // Read package.json to detect framework
  const pkgContent = await gh.getFileContent(token, owner, repo, "package.json", ref);
  if (!pkgContent) return null;

  try {
    const pkg = JSON.parse(pkgContent);
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    const scripts = pkg.scripts ?? {};

    // Detect test command
    let testCommand = "npx playwright test --reporter=list";
    if (deps["@playwright/test"]) {
      testCommand = scripts["test:e2e"] ?? "npx playwright test --reporter=list";
    } else if (deps.cypress) {
      testCommand = "npx cypress run";
    } else if (deps.vitest && scripts["test"]) {
      testCommand = scripts["test"];
    } else {
      // No E2E framework found
      return null;
    }

    // Detect framework — order matters, check meta-frameworks before libs.
    let framework: E2EConfig["framework"] = "generic";
    let startCommand = scripts.start ?? "npm start";
    let port = 3000;
    let buildCommand = scripts.build ? "npm run build" : "npm run build --if-present";

    if (deps.next) {
      framework = "nextjs";
      startCommand = "npx next start";
      port = 3000;
      buildCommand = "npx next build";
    } else if (deps.nuxt || deps["nuxt3"]) {
      framework = "nuxt";
      startCommand = "node .output/server/index.mjs";
      port = 3000;
      buildCommand = "npx nuxt build";
    } else if (deps["@remix-run/serve"] || deps["@remix-run/node"] || deps["@remix-run/react"]) {
      framework = "remix";
      startCommand = scripts.start ?? "npx remix-serve build/server/index.js";
      port = 3000;
      buildCommand = "npx remix vite:build";
    } else if (deps["@sveltejs/kit"]) {
      framework = "sveltekit";
      startCommand = "node build/index.js";
      port = 3000;
      buildCommand = "npx vite build";
    } else if (deps.astro) {
      framework = "astro";
      startCommand = "node ./dist/server/entry.mjs";
      port = 4321;
      buildCommand = "npx astro build";
    } else if (deps["@nestjs/core"] || deps["@nestjs/common"]) {
      framework = "nest";
      startCommand = scripts["start:prod"] ?? "node dist/main.js";
      port = 3000;
      buildCommand = scripts.build ? "npm run build" : "npx nest build";
    } else if (deps.fastify) {
      framework = "fastify";
      startCommand = scripts.start ?? "node dist/index.js";
      port = 3000;
    } else if (deps.express) {
      framework = "express";
      startCommand = scripts.start ?? "node dist/index.js";
      port = 3000;
    } else if (deps.vite) {
      // Vite without a known meta-framework — likely an SPA or SSR app.
      framework = "vite";
      startCommand = scripts.preview ? "npm run preview -- --port 4173 --host" : "npx vite preview --port 4173 --host";
      port = 4173;
      buildCommand = "npx vite build";
    }

    // Detect package manager
    let installCommand = "npm ci";
    const files = await gh.getRepoTree(token, owner, repo, ref);
    if (files.includes("pnpm-lock.yaml")) installCommand = "pnpm install --frozen-lockfile";
    else if (files.includes("yarn.lock")) installCommand = "yarn install --frozen-lockfile";
    else if (files.includes("bun.lockb")) installCommand = "bun install";

    return { framework, startCommand, port, testCommand, installCommand, buildCommand };
  } catch {
    return null;
  }
}

// ── Generate E2E workflow ────────────────────────────────────────────────────

export function generateE2EWorkflow(config: E2EConfig): { path: string; content: string } {
  // Validate port is safe
  if (config.port < 1024 || config.port > 65535) config.port = 3000;
  const workflow = `# Auto-generated by InariWatch — Staging E2E Verification
# Builds the app with the fix, starts it, and runs E2E tests.
# If tests fail, the fix likely introduces regressions.

name: InariWatch E2E Staging

on:
  push:
    branches: ['radar/fix-*']

jobs:
  e2e-staging:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_ENV: test
      CI: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: ${config.installCommand}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        continue-on-error: true

      - name: Build
        run: ${config.buildCommand}
        env:
          NODE_ENV: test

      - name: Start application
        run: |
          ${config.startCommand} &
          APP_PID=$!
          echo "APP_PID=$APP_PID" >> $GITHUB_ENV

          # Wait for app to be ready (max 60s)
          echo "Waiting for app on port ${config.port}..."
          for i in $(seq 1 30); do
            if curl -sf http://localhost:${config.port}/ > /dev/null 2>&1; then
              echo "App is ready after $((i * 2))s"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "::warning::App did not start within 60s — running tests anyway"
            fi
            sleep 2
          done
        env:
          PORT: '${config.port}'

      - name: Run E2E tests
        run: ${config.testCommand}
        env:
          BASE_URL: 'http://localhost:${config.port}'
          PLAYWRIGHT_BASE_URL: 'http://localhost:${config.port}'

      - name: Stop application
        if: always()
        run: |
          if [ -n "$APP_PID" ]; then
            kill $APP_PID 2>/dev/null || true
          fi

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results
          path: |
            test-results/
            playwright-report/
          retention-days: 7
`;

  return {
    path: ".github/workflows/inariwatch-e2e-staging.yml",
    content: workflow,
  };
}

// ── Push workflow to fix branch ──────────────────────────────────────────────

export async function pushE2EWorkflow(
  token: string,
  owner: string,
  repo: string,
  branch: string,
  config: E2EConfig
): Promise<boolean> {
  try {
    const workflow = generateE2EWorkflow(config);

    await gh.commitFiles(token, owner, repo, branch, "ci: add InariWatch E2E staging verification", [workflow]);
    return true;
  } catch {
    return false;
  }
}

// ── Wait for E2E check run result ────────────────────────────────────────────

export async function waitForE2EResult(
  token: string,
  owner: string,
  repo: string,
  ref: string,
  timeoutMs: number = 600_000 // 10 min
): Promise<E2EResult | null> {
  const startTime = Date.now();
  const checkName = "e2e-staging"; // matches the job name in the workflow

  while (Date.now() - startTime < timeoutMs) {
    const result = await gh.getCheckRunsStatus(token, owner, repo, ref);

    // Find our specific check
    const e2eCheck = result.details.find(
      (d) => d.name.includes("e2e") || d.name.includes("E2E") || d.name.includes("staging")
    );

    if (e2eCheck) {
      if (e2eCheck.status === "completed") {
        return {
          passed: e2eCheck.conclusion === "success",
          testCount: 0, // GitHub API doesn't expose test counts
          failedCount: e2eCheck.conclusion === "failure" ? 1 : 0,
          duration: Math.round((Date.now() - startTime) / 1000),
          logs: `E2E check "${e2eCheck.name}": ${e2eCheck.conclusion ?? "unknown"}`,
        };
      }
    }

    // Wait 20 seconds between polls (E2E takes longer than unit tests)
    await new Promise((r) => setTimeout(r, 20_000));
  }

  return null; // timeout
}
