/**
 * Inari Guard — test file delivery modes.
 *
 * Once a generation succeeds (status="ready"), the user can choose how
 * the test file actually lands:
 *
 *   - "pr"     → push the test on a new branch, open a draft PR.
 *                The user reviews + merges on GitHub.
 *   - "local"  → return the test inline; the desktop app writes it to
 *                the user's local clone via the same Fix Locally setting
 *                (`project_local_path_<projectId>`). This module just
 *                packages the response — the actual disk write happens
 *                in Tauri.
 *   - "inline" → return the test in the API response body, do nothing
 *                else. The user copies it manually.
 *
 * Default delivery is "inline" — opt-in to PR / local to avoid silent
 * git pushes.
 */

import * as gh from "@/lib/services/github-api";

export type DeliveryMode = "inline" | "pr" | "local";

export interface DeliveryResult {
  mode: DeliveryMode;
  /** Set when mode === "pr". */
  prUrl?: string;
  prNumber?: number;
  branchName?: string;
  /** Set when mode === "local". The Tauri client writes to this path. */
  localPath?: string;
  /** Always set. The test path inside the repo. */
  testPath: string;
  error?: string;
}

export interface PRDeliveryArgs {
  testFile: { path: string; content: string };
  alertTitle?: string;
  sessionId: string;
  /** GitHub PAT or App token. */
  token: string;
  owner: string;
  repo: string;
  defaultBranch: string;
  /** When generation was alert-driven, link the alert in the PR body. */
  alertId?: string;
}

/**
 * Push a generated test as a draft PR. Branch naming follows the
 * pattern Inari uses for remediations: `inari-guard/<sessionId-prefix>`.
 *
 * Idempotent within a session — if the branch already exists, we
 * commit on top instead of creating fresh. If the PR already exists,
 * we return its URL/number.
 *
 * Throws on any GitHub API failure with a human-readable message.
 */
export async function deliverViaPR(args: PRDeliveryArgs): Promise<DeliveryResult> {
  const branchName = `inari-guard/${args.sessionId.slice(0, 8)}-${slugifyPath(args.testFile.path)}`;
  const titleSubject = args.alertTitle ? `regression test for ${args.alertTitle.slice(0, 50)}` : `tests for ${args.testFile.path}`;
  const title = `test: ${titleSubject}`;

  // Create branch off the default. createBranch is non-idempotent
  // (errors when branch already exists), so we catch & continue.
  const baseSha = await gh.getBranchSha(args.token, args.owner, args.repo, args.defaultBranch);
  try {
    await gh.createBranch(args.token, args.owner, args.repo, branchName, baseSha);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    // 422 with "Reference already exists" is fine — we'll just commit on top.
    if (!/already exists/i.test(msg) && !/422/.test(msg)) throw err;
  }

  // Commit the test file (commitFiles signature: token, owner, repo, branch, message, files)
  await gh.commitFiles(
    args.token,
    args.owner,
    args.repo,
    branchName,
    `test: ${args.testFile.path}\n\nGenerated by Inari Guard${args.alertId ? ` for alert ${args.alertId.slice(0, 8)}` : ""}.`,
    [{ path: args.testFile.path, content: args.testFile.content }],
  );

  // Open the PR (draft so the user reviews before merging)
  const prBody = [
    "🦊 Generated by **Inari Guard** — AI test generation pipeline.",
    "",
    "## What this PR does",
    "",
    `Adds \`${args.testFile.path}\` with regression tests generated by the Inari Guard three-pass pipeline (plan → write → review) plus deterministic quality gates.`,
    "",
    args.alertId
      ? `## Source\n\nGenerated from [alert ${args.alertId.slice(0, 8)}](${process.env.APP_URL ?? "https://app.inariwatch.com"}/alerts/${args.alertId}). The tests cover the code path implicated in that alert's stack trace.\n\n`
      : "",
    "## Quality gates passed",
    "",
    "- ✅ Every `it()`/`test()` block has at least one assertion",
    "- ✅ No trivial assertions (`expect(true).toBe(true)` rejected)",
    "- ✅ No hardcoded waits (`waitForTimeout` / `sleep` rejected)",
    "- ✅ Test names describe behavior, not implementation",
    "- ✅ Test file references at least one source export",
    "- ✅ File size under 500 LOC",
    "",
    "## Review",
    "",
    `Full pipeline detail (plan, model breakdown, reviewer verdict) at [${process.env.APP_URL ?? "https://app.inariwatch.com"}/tests/${args.sessionId}](${process.env.APP_URL ?? "https://app.inariwatch.com"}/tests/${args.sessionId}).`,
    "",
    "Verify the tests fail when the source bug is reverted, then merge.",
    "",
    "---",
    `<sub>Session \`${args.sessionId}\` · Inari Guard</sub>`,
  ]
    .filter(Boolean)
    .join("\n");

  let pr: { url: string; number: number };
  try {
    pr = await gh.createPR(
      args.token,
      args.owner,
      args.repo,
      title,
      prBody,
      branchName,
      args.defaultBranch,
      true, // draft
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    // If a PR already exists for this branch, treat as success and try
    // to look it up. (Rare path — only on re-runs of the same session.)
    if (/already exists/i.test(msg) || /A pull request already exists/i.test(msg)) {
      return {
        mode: "pr",
        testPath: args.testFile.path,
        branchName,
        error: "PR for this branch already exists — re-check Pull Requests on the repo",
      };
    }
    throw err;
  }

  return {
    mode: "pr",
    prUrl: pr.url,
    prNumber: pr.number,
    branchName,
    testPath: args.testFile.path,
  };
}

/**
 * Slugify a file path for use in a git branch name.
 * "src/lib/auth.ts" → "src-lib-auth-ts"
 */
function slugifyPath(path: string): string {
  return path
    .replace(/[\/\\]/g, "-")
    .replace(/[^a-zA-Z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
    .slice(0, 50);
}
