// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AboutInfo = { version: string, commit: string | null, 
/**
 * `stable` / `beta`.
 */
channel: string, 
/**
 * Unix ms of the last update check (0 = never).
 */
last_update_check_ms: bigint, };