// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiSettings = { 
/**
 * Truthy when a BYOK key is on disk. Raw key NEVER returned.
 */
byok_present: boolean, 
/**
 * Last 4 chars of the BYOK key for "still configured" affordances.
 * Empty when no key is set.
 */
byok_preview: string, 
/**
 * `auto` / `always_mini` / `always_full`. Defaults to `auto`.
 */
model_routing: string, 
/**
 * Hardcoded read-only display today; Sesión 18 wires real billing.
 */
spend_today_usd: number, spend_cap_usd: number, 
/**
 * Sesión 25 — Fast Apply via local Kortix FastApply-7B. False by
 * default. Reading the toggle is cheap (a settings table lookup);
 * writing requires the hardware tier ≥ 2 + the GGUF pre-downloaded.
 * Both prerequisites are validated inside `run_single_shot`'s local
 * branch, NOT here — the toggle just expresses user intent.
 */
local_apply_enabled: boolean, };