// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "..\\..\\..\\src-tauri\\bindings\\serde_json\\JsonValue";
import type { UsagePayload } from "./UsagePayload";

export type Block = { "kind": "user", id: string, created_at: number, content: string, } | { "kind": "reasoning", id: string, created_at: number, content: string, 
/**
 * True while `thinking_delta`s still arrive for this block.
 */
streaming: boolean, 
/**
 * Heuristic estimate (chars/4); not authoritative — the model
 * usage payload is.
 */
token_count: number | null, } | { "kind": "assistant", id: string, created_at: number, content: string, streaming: boolean, } | { "kind": "tool_use", id: string, created_at: number, tool_use_id: string, tool_name: string, input: JsonValue, pending: boolean, } | { "kind": "tool_result", id: string, created_at: number, tool_use_id: string, output: JsonValue, is_error: boolean, } | { "kind": "error", id: string, created_at: number, error_kind: string, message: string, hint: string | null, } | { "kind": "system", id: string, created_at: number, subtype: string, summary: string, } | { "kind": "result", id: string, created_at: number, subtype: string, result: string | null, total_cost_usd: number | null, duration_ms: number | null, usage: UsagePayload | null, is_error: boolean, } | { "kind": "summary", id: string, created_at: number, 
/**
 * Number of original turns this summary replaces.
 */
turn_count: number, 
/**
 * Approximate byte count of the elided turns. Surfaced in
 * the badge so users know how much content is folded behind
 * the click-to-expand.
 */
bytes_elided: number, 
/**
 * The summarizer's bullet-point body.
 */
summary_text: string, 
/**
 * SQLite archive lookup key — session.
 */
archive_session_id: string, 
/**
 * SQLite archive lookup key — per-session monotonic
 * compaction id.
 */
archive_compaction_id: number, };