// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientStatusDto = { client: string, installed: boolean, path: string, matches_current: boolean, };