// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactionTurn } from "./CompactionTurn";

/**
 * Output of a successful compaction. Persisted via [`persist_archive`].
 */
export type CompactionResult = { session_id: string, compaction_id: number, ts_unix_ms: number, original_turns: Array<CompactionTurn>, summary_text: string, estimated_tokens_saved: number, summarizer_model: string, provider: string, };