// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One conversation turn for the compaction layer's view of the
 * transcript. Lighter-weight than the full Block enum because the
 * summarizer only needs role + text + token count.
 */
export type CompactionTurn = { 
/**
 * `"user"` | `"assistant"` | `"tool"` (rare — used when an MCP
 * tool result alone is large enough to be its own "turn"). The
 * summarizer prompt embeds the role verbatim.
 */
role: string, 
/**
 * The turn's textual body. For tool turns this is the
 * JSON-serialized result.
 */
content: string, 
/**
 * Approximate token count (chars / 4 heuristic — same rule
 * the rest of the optimizer uses for cost-of-being-wrong
 * estimates). Authoritative for `should_compact`.
 */
tokens: number, };