// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextLayerDto } from "./ContextLayerDto";

export type ContextStackDto = { layers: Array<ContextLayerDto>, total_bytes: number, truncated: boolean, };