// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DaemonStatusDto = { uptime_secs: bigint, sensor_count: number, repo_count: number, 
/**
 * Build version (`CARGO_PKG_VERSION`).
 */
version: string, 
/**
 * ISO-8601 UTC at which the daemon spawned.
 */
started_at: string, };