// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneralSettings = { 
/**
 * `auto` / `light` / `dark`.
 */
theme: string, 
/**
 * `en` / `es` (initial). Forward-compat: arbitrary BCP-47 string.
 */
language: string, sound_on_critical: boolean, };