// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHookInstallDto = { installed: Array<string>, backed_up: Array<string>, already_ours: Array<string>, hook_dir: string, };