// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHookStatusDto = { repo_id: string, installed: boolean, hook_files: Array<string>, hook_dir: string, port: number, };