// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitHookUninstallDto = { removed: Array<string>, restored: Array<string>, absent: Array<string>, hook_dir: string, };