// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogEntryDto = { 
/**
 * Original line, untouched.
 */
raw: string, 
/**
 * Parsed level (`debug` / `info` / `warn` / `error`) when the line
 * matches the tracing-fmt format; `unknown` otherwise.
 */
level: string, 
/**
 * Resolved file path the line came from. Useful for diagnosing
 * rotated-vs-current log issues.
 */
file: string, };