// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Settings UI shows beside "Inari Live MCP" — a port and a
 * Bearer token. Token is the raw value; UI is responsible for the
 * "Copy" button + masking. Port is read-only (server picks at boot
 * via fallback).
 */
export type McpAuthDto = { token: string, port: number, created_at: bigint, };