// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryMdDto = { content: string, 
/**
 * Bytes on disk at read time. Cheap consistency check for the UI.
 */
size_bytes: bigint, 
/**
 * Provenance of the latest persisted version (`ai`, `merge`, …),
 * or `None` when no version row exists yet.
 */
written_by: string | null, written_at: bigint | null, };