// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Navigate the requested webview surface to `route`. The frontend
 * listens to `inari://navigate` per Sesión 14 and pivots its visible
 * route based on `target` + the current webview label.
 */
export type NavigatePayload = { target: string, route: string, };