// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationsSettings = { 
/**
 * `silent` / `important` / `all`.
 */
notification_level: string, 
/**
 * 0–100.
 */
sound_volume: number, 
/**
 * "HH:MM" — empty when quiet hours are off.
 */
quiet_hours_start: string, quiet_hours_end: string, 
/**
 * IANA tz, e.g. `America/Mexico_City`. Empty = system default.
 */
quiet_hours_tz: string, respect_focus_mode: boolean, };