// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OnboardingProgressDto = { 
/**
 * `scanning` (initial walk) / `indexing` (embedding pass) / `done`.
 */
stage: string, 
/**
 * 0.0–1.0 — heuristic, monotonically non-decreasing.
 */
percent: number, symbol_count: bigint, };