// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated savings across a window of turns. Used by both the
 * "live" summary (open sessions) and the "history" summary.
 */
export type OptimizerSummary = { 
/**
 * Number of turns aggregated.
 */
turn_count: number, 
/**
 * Number of distinct sessions touched.
 */
session_count: number, total_cost_usd: number, total_baseline_cost_usd: number, total_input_tokens_cached: number, total_input_tokens_uncached: number, total_output_tokens: number, 
/**
 * Equivalent of [`OptimizerTurn::savings_ratio`] across the window.
 * Returns 0 when baseline is 0.
 */
savings_ratio: number, 
/**
 * Split of turn rows by `optimizer_enabled` flag. Lets the panel
 * render the "with vs without" comparison without a second query.
 */
turns_with_optimizer: number, turns_without_optimizer: number, };