// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One persisted row of [`inari_live_optimizer_metrics`].
 */
export type OptimizerTurn = { session_id: string, turn_index: number, ts_unix_ms: number, input_tokens_cached: number, input_tokens_uncached: number, cache_creation_tokens: number, output_tokens: number, cost_usd: number, baseline_cost_usd: number, optimizer_enabled: boolean, model: string, provider: string, };