// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoSummaryDto = { id: string, path: string, name: string, opened_at_ms: bigint, last_indexed_at_ms: bigint | null, indexed_file_count: bigint, symbol_count: bigint, replay_enabled: boolean, };