// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SensorsState = { fs_enabled: boolean, 
/**
 * MCP server is always-on by design (Sesión 7). Reported here so
 * the UI can render an immutable "Always on" badge without an
 * additional round-trip.
 */
mcp_always_on: boolean, shell_installed: Array<string>, git_hooks_count: number, http_proxy_enabled: boolean, http_proxy_port: number, 
/**
 * Aggregate replay flag — true when at least one repo has
 * `replay_enabled = true`.
 */
substrate_any_repo: boolean, };