// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Successful transcription result. The `engine` field is surfaced so
 * telemetry / receipts can tell at a glance whether a real Whisper
 * run produced the text or a mock did (test paths).
 */
export type TranscriptionResult = { text: string, 
/**
 * `whisper_cli` for the production path, `mock` for tests.
 */
engine: string, 
/**
 * Approximate audio length in milliseconds (parsed from the WAV
 * header). Surfaced in the UI alongside the transcript.
 */
audio_duration_ms: number, };