// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateCheckResult = { 
/**
 * `idle` (no update), `pending` (download in flight), `ready` (apply on restart).
 */
status: string, message: string, checked_at_ms: bigint, };