// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage breakdown from a `result` event.
 *
 * Also reused inside [`crate::inari_live::blocks::Block::Result`]; the
 * `TS` derive (S4) propagates to `Block.ts` automatically because
 * ts-rs follows the field type recursively.
 */
export type UsagePayload = { input_tokens: number, cache_creation_input_tokens: number, cache_read_input_tokens: number, output_tokens: number, };