// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-facing voice settings. The frontend reads/writes the full
 * snapshot through a single round-trip — settings are tiny, partial
 * patches aren't worth the surface-area cost.
 */
export type VoiceSettings = { 
/**
 * Master toggle for STT (mic button rendered in chat input).
 */
input_enabled: boolean, 
/**
 * Master toggle for TTS (auto-speak surface enabled).
 */
output_enabled: boolean, 
/**
 * Override the default whisper model path. Empty = use default.
 */
stt_model_path: string, 
/**
 * Selected Piper voice id. Empty = use registry default.
 */
tts_voice: string, 
/**
 * When `output_enabled` is true, automatically speak assistant
 * responses. Independent flag so users can keep the surface
 * available (Test speak, manual playback) without auto-firing.
 */
auto_speak_responses: boolean, 
/**
 * Push-to-talk mode (hold mic button) vs click-toggle hands-free.
 */
push_to_talk: boolean, };