// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WipeRepoMemoryResult = { repo_id: string, symbols: bigint, embeddings: bigint, events: bigint, patterns: bigint, };